platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: "3.6"

inputs:
  - name: git-repo

outputs:
  - name: settings
  - name: docker-folder

params:
  nexusDeployUsername: ((telia-nexus-iot-deploy-username))
  nexusDeployPassword: ((telia-nexus-iot-deploy-password))

run:
  path: git-repo/ci/tasks/make-settings/task.sh
