platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: "3.6"

inputs:
  - name: git-repo

outputs:
  - name: settings
  - name: docker-folder

params:
  nexusSnapshotDeployUsername: ((nexus-iot-snapshot-deploy.username))
  nexusShapshotDeployPassword: ((nexus-iot-snapshot-deploy.password))

run:
  path: git-repo/ci/tasks/make-settings/task.sh
