platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: "3.6"

inputs:
  - name: git-repo
  - name: jar-file

outputs:
  - name: docker-folder
    path: docker-folder/

run:
  path: git-repo/ci/tasks/prepare-docker/task.sh