platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: alpine

inputs:
  - name: git-repo
  - name: settings


#outputs:
#  - name: jar-file
#    path: git-repo/target/

run:
  path: mvn
  args: ["-f", "git-repo/pom.xml", "--settings", "settings/settings.xml", "deploy"]