platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: "3.6"

inputs:
  - name: git-repo
  - name: jar-file


run:
  path: git-repo/ci/tasks/docker-build/task.sh