platform: linux

image_resource:
  type: docker-image
  source:
    repository: guss77/dind-awscli
    tag: "latest"

inputs:
  - name: git-repo
  - name: jar-file


run:
  path: git-repo/ci/tasks/docker-build/task.sh