platform: linux

image_resource:
  type: docker-image
  source:
    repository: colincoleman/snyk-for-concourse
    tag: "maven-3.5.2"

inputs:
  - name: git-repo

run:
  path: git-repo/ci/tasks/snyk/task.sh

params:
  nexusSnapshotDeployUsername: ((colinsnyktoken))