platform: linux

image_resource:
  type: docker-image
  source:
    repository: snyk/snyk-cli
    tag: "1.69.4-maven-3.5.2"

inputs:
  - name: git-repo

run:
  path: test

params:
  PROJECT_PATH: /git-repo