platform: linux

image_resource:
  type: docker-image
  source:
    repository: snyk/snyk-cli
    tag: "maven-3.5.2"

inputs:
  - name: git-repo

params:
  PROJECT_PATH: /git-repo
run:
  path: git-repo/test