resources:
  - name: git-repo
    type: git
    source:
      uri: git@github.com:colincoleman/Terraform-CI-POC.git
      branch: master
      private_key: ((terraform-ci-poc-git-deploy-key))

  - name: terraform-ci-poc-docker-image
    type: docker-image
    source:
      repository: 653090749433.dkr.ecr.eu-west-1.amazonaws.com/terraform-ci-poc
      aws_access_key_id: ((machineuserkey))
      aws_secret_access_key: ((machineusersecret))



jobs:
  - name: test-dependencies
    plan:
    - aggregate:
      - get: git-repo
        trigger: true
    - task: snyk
      params:
        SNYK_TOKEN: ((colinsnyktoken))
      file: git-repo/ci/tasks/snyk/task.yml

  - name: deploy
    plan:
    - aggregate:
      - get: git-repo
        trigger: true
    - task: make-settings
      privileged: true
      file: git-repo/ci/tasks/make-settings/task.yml
    - task: maven-deploy
      privileged: true
      file: git-repo/ci/tasks/maven-deploy/task.yml
    - task: prepare-docker
      privileged: true
      file: git-repo/ci/tasks/prepare-docker/task.yml
    - put: terraform-ci-poc-docker-image
      params:
        build: docker-folder/docker
        skip_download: true
      get_params: {skip_download: true}
    - task: deploy-to-dev
      params:
        AWS_ACCESS_KEY_ID: ((telia-divx-xqb-dev-access-key))
        AWS_SECRET_ACCESS_KEY: ((telia-divx-xqb-dev-secret-key))
        AWS_SESSION_TOKEN: ((telia-divx-xqb-dev-session-token))
      file: git-repo/ci/tasks/deploy-to-dev/task.yml



