resources:
  - name: git-repo
    type: git
    source:
      uri: https://github.com/colincoleman/Terraform-CI-POC.git
      branch: master
      private_key: ((terraform-ci-poc-git-deploy-key))

  - name: terraform-ci-poc-docker-image
    type: docker-image
    source:
      repository: 752583717420.dkr.ecr.eu-west-1.amazonaws.com/terraform-ci-poc
      aws_access_key_id: ((cloudops_deployer_access_key_id))
      aws_secret_access_key: ((cloudops_deployer_secret_access_key))



jobs:
  - name: maven-deploy
    plan:
    - aggregate:
      - get: git-repo
        trigger: true
    - task: make-settings
      privileged: true
      file: git-repo/ci/tasks/make-settings/task.yml
    - task: maven-deploy
      privileged: true
      file: git-repo/ci/tasks/maven-deploy/task.yml
    - task: prepare-docker
      privileged: true
      file: git-repo/ci/tasks/prepare-docker/task.yml
    - put: terraform-ci-poc-docker-image
      params:
        build: docker-folder/docker
        skip_download: true