resources:
  - name: git-repo
    type: git
    source:
      uri: https://github.com/colincoleman/Terraform-CI-POC.git
      branch: master
      private_key: ((telia-terraform-ci-poc-deploy-key))
  - name: every-60s
    type: time
    source:
      interval: 60s


jobs:
  - name: maven-deploy
    plan:
    - aggregate:
      - get: git-repo
        trigger: true
      - get: every-60s
#    - task: make-settings
#      file: git-repo/ci/tasks/make-settings.yml
    - task: maven-deploy
      privileged: true
      file: git-repo/ci/tasks/maven-deploy.yml